### ISSUE TITLE
Error in MinHashSampler ("_create_minhash_pairs") when length of words within string compared are all equal to 1

### ISSUE THREAD

**Issue by gregskol** [fritshermans/deduplipy#18]
Hi and thank you for creating the package!
I am exploring its applicability on a data set and I run into an error.
The data that I am using come from an ERP, so the user can insert whatever he wants sometimes erroneous data.
I identified that when all words lengths within the string to be compared are equal to 1 I get an error on the MinHashSampler when trying to fit.
I reproduced the error on an artificial dataset please see below:

----------------------------------------------------------------------------------------------

> def first_two_characters(x):
>     return x[:2]

> df = pd.DataFrame(
>     data = [['george d'],['andy t'],['greg b'],['ret'],['pam'],['kos'],['andy'],
>     ['pamela'],['pamla'],['kis'],['paul'],['paul d'],
>     ['geirge d'],['ndy t'],['greg'],['retos'],['pipo'],['konstas'],['grig'],['gre']
>     ,['k i']
>     ],
>     columns = ['name'])
> field_info = {'name':[ratio]}
> myDedupliPy = Deduplicator(
>     field_info=field_info, 
>     interaction=False, 
>     rules={'name': [first_two_characters]},
>     verbose=1)
> myDedupliPy.fit(X = df[['name']],n_samples = 100)

----------------------------------------------------------------------------------------------

If I remove the ['k i'] row it runs without errors.
The error occurs when the MinHashSampler is called but I am not sure exactly what the function does and how to correct that.

I suppose that I could perform a check, for example counting the length of words of each row and omitting them, before calling the function but I wanted to check with you if you have any suggestion and recipes?

Thank you very much in advance,

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)

File ~/miniconda2/envs/py395dd/lib/python3.9/site-packages/deduplipy/deduplicator/deduplicator.py:136, in Deduplicator.fit(self, X, n_samples)
    ]()[124](file:///~/miniconda2/envs/py395dd/lib/python3.9/site-packages/deduplipy/deduplicator/deduplicator.py?line=123)[ def fit(self, X: pd.DataFrame, n_samples: int = 10_000) -> 'Deduplicator':
    ]()[125](file:///~/miniconda2/envs/py395dd/lib/python3.9/site-packages/deduplipy/deduplicator/deduplicator.py?line=124)[     """
    ]()[126](file:///~/miniconda2/envs/py395dd/lib/python3.9/site-packages/deduplipy/deduplicator/deduplicator.py?line=125)[     Fit the deduplicator instance
    ]()[127](file:///~/miniconda2/envs/py395dd/lib/python3.9/site-packages/deduplipy/deduplicator/deduplicator.py?line=126)[ 
   (...)
    ]()[134](file:///~/miniconda2/envs/py395dd/lib/python3.9/site-packages/deduplipy/deduplicator/deduplicator.py?line=133)[ 
    ]()[135](file:///~/miniconda2/envs/py395dd/lib/python3.9/site-packages/deduplipy/deduplicator/deduplicator.py?line=134)[     """
--> ]()[136](file:///~/miniconda2/envs/py395dd/lib/python3.9/site-packages/deduplipy/deduplicator/deduplicator.py?line=135)[     pairs_table = self._create_pairs_table(X, n_samples)
    ]()[137](file:///~/miniconda2/envs/py395dd/lib/python3.9/site-packages/deduplipy/deduplicator/deduplicator.py?line=136)[     similarities = self._calculate_string_similarities(pairs_table)
    ]()[138](file:///~/miniconda2/envs/py395dd/lib/python3.9/site-packages/deduplipy/deduplicator/deduplicator.py?line=137)[     self.myActiveLearner.fit(similarities)

File ~/miniconda2/envs/py395dd/lib/python3.9/site-packages/deduplipy/deduplicator/deduplicator.py:105, in Deduplicator._create_pairs_table(self, X, n_samples)
     ]()[93](file:///~/miniconda2/envs/py395dd/lib/python3.9/site-packages/deduplipy/deduplicator/deduplicator.py?line=92)[ """
     ]()[94](file:///~/miniconda2/envs/py395dd/lib/python3.9/site-packages/deduplipy/deduplicator/deduplicator.py?line=93)[ Create sample of pairs
     ]()[95](file:///~/miniconda2/envs/py395dd/lib/python3.9/site-packages/deduplipy/deduplicator/deduplicator.py?line=94)[ 
   (...)
    ]()[102](file:///~/miniconda2/envs/py395dd/lib/python3.9/site-packages/deduplipy/deduplicator/deduplicator.py?line=101)[ 
    ]()[103](file:///~/miniconda2/envs/py395dd/lib/python3.9/site-packages/deduplipy/deduplicator/deduplicator.py?line=102)[ """
    ]()[104](file:///~/miniconda2/envs/py395dd/lib/python3.9/site-packages/deduplipy/deduplicator/deduplicator.py?line=103)[ n_samples_minhash = n_samples // 2
--> ]()[105](file:///~/miniconda2/envs/py395dd/lib/python3.9/site-packages/deduplipy/deduplicator/deduplicator.py?line=104)[ minhash_pairs = MinHashSampler(self.col_names).sample(X, n_samples_minhash)
    ]()[106](file:///~/miniconda2/envs/py395dd/lib/python3.9/site-packages/deduplipy/deduplicator/deduplicator.py?line=105)[ # the number of minhash samples can be (much) smaller than n_samples//2, in such case take more random pairs:
    ]()[107](file:///~/miniconda2/envs/py395dd/lib/python3.9/site-packages/deduplipy/deduplicator/deduplicator.py?line=106)[ n_samples_naive = n_samples - len(minhash_pairs)

File ~/miniconda2/envs/py395dd/lib/python3.9/site-packages/deduplipy/sampling/minhash_sampling.py:128, in MinHashSampler.sample(self, X, n_samples, threshold)
    ]()[114](file:///~/miniconda2/envs/py395dd/lib/python3.9/site-packages/deduplipy/sampling/minhash_sampling.py?line=113)[ def sample(self, X: pd.DataFrame, n_samples: int, threshold: float = 0.2) -> pd.DataFrame:
    ]()[115](file:///~/miniconda2/envs/py395dd/lib/python3.9/site-packages/deduplipy/sampling/minhash_sampling.py?line=114)[     """
    ]()[116](file:///~/miniconda2/envs/py395dd/lib/python3.9/site-packages/deduplipy/sampling/minhash_sampling.py?line=115)[     Method to draw sample of pairs of size `n_samples` from dataframe X. Note that `n_samples` cannot be returned if
    ]()[117](file:///~/miniconda2/envs/py395dd/lib/python3.9/site-packages/deduplipy/sampling/minhash_sampling.py?line=116)[     the number of pairs above the threshold is too low.
   (...)
    ]()[126](file:///~/miniconda2/envs/py395dd/lib/python3.9/site-packages/deduplipy/sampling/minhash_sampling.py?line=125)[ 
    ]()[127](file:///~/miniconda2/envs/py395dd/lib/python3.9/site-packages/deduplipy/sampling/minhash_sampling.py?line=126)[     """
--> ]()[128](file:///~/miniconda2/envs/py395dd/lib/python3.9/site-packages/deduplipy/sampling/minhash_sampling.py?line=127)[     minhash_pairs = self._create_minhash_pairs(X, threshold)
    ]()[130](file:///~/miniconda2/envs/py395dd/lib/python3.9/site-packages/deduplipy/sampling/minhash_sampling.py?line=129)[     stratified_sample = self._get_stratified_sample(minhash_pairs, n_samples)
    ]()[132](file:///~/miniconda2/envs/py395dd/lib/python3.9/site-packages/deduplipy/sampling/minhash_sampling.py?line=131)[     non_stratified_sample = self._get_non_stratified_sample(minhash_pairs, stratified_sample, n_samples)

File ~/miniconda2/envs/py395dd/lib/python3.9/site-packages/deduplipy/sampling/minhash_sampling.py:49, in MinHashSampler._create_minhash_pairs(self, X, threshold)
     ]()[47](file:///~/miniconda2/envs/py395dd/lib/python3.9/site-packages/deduplipy/sampling/minhash_sampling.py?line=46)[ minhash_pairs = pd.DataFrame()
     ]()[48](file:///~/miniconda2/envs/py395dd/lib/python3.9/site-packages/deduplipy/sampling/minhash_sampling.py?line=47)[ for col in self.col_names:
---> ]()[49](file:///~/miniconda2/envs/py395dd/lib/python3.9/site-packages/deduplipy/sampling/minhash_sampling.py?line=48)[     minhash_result = self.MinHasher.fit_predict(df, col)
     ]()[51](file:///~/miniconda2/envs/py395dd/lib/python3.9/site-packages/deduplipy/sampling/minhash_sampling.py?line=50)[     # add other columns than the one used for minhashing
     ]()[52](file:///~/miniconda2/envs/py395dd/lib/python3.9/site-packages/deduplipy/sampling/minhash_sampling.py?line=51)[     minhash_result = (minhash_result
     ]()[53](file:///~/miniconda2/envs/py395dd/lib/python3.9/site-packages/deduplipy/sampling/minhash_sampling.py?line=52)[                       .merge(df.drop(columns=[col]), left_on='row_number_1', right_on='row_number')
     ]()[54](file:///~/miniconda2/envs/py395dd/lib/python3.9/site-packages/deduplipy/sampling/minhash_sampling.py?line=53)[                       .drop(columns=['row_number']))

File ~/miniconda2/envs/py395dd/lib/python3.9/site-packages/pyminhash/pyminhash.py:154, in MinHash.fit_predict(self, df, col_name)
    ]()[152](file:///~/miniconda2/envs/py395dd/lib/python3.9/site-packages/pyminhash/pyminhash.py?line=151)[     df_['row_number'] = np.arange(len(df_))
    ]()[153](file:///~/miniconda2/envs/py395dd/lib/python3.9/site-packages/pyminhash/pyminhash.py?line=152)[ df_ = self._sparse_vectorize(df_, col_name)
--> ]()[154](file:///~/miniconda2/envs/py395dd/lib/python3.9/site-packages/pyminhash/pyminhash.py?line=153)[ df_ = self._create_minhash_signatures(df_)
    ]()[155](file:///~/miniconda2/envs/py395dd/lib/python3.9/site-packages/pyminhash/pyminhash.py?line=154)[ return self._create_pairs(df_, col_name)

File ~/miniconda2/envs/py395dd/lib/python3.9/site-packages/pyminhash/pyminhash.py:88, in MinHash._create_minhash_signatures(self, df)
     ]()[76](file:///~/miniconda2/envs/py395dd/lib/python3.9/site-packages/pyminhash/pyminhash.py?line=75)[ def _create_minhash_signatures(self, df: pd.DataFrame) -> pd.DataFrame:
     ]()[77](file:///~/miniconda2/envs/py395dd/lib/python3.9/site-packages/pyminhash/pyminhash.py?line=76)[     """
     ]()[78](file:///~/miniconda2/envs/py395dd/lib/python3.9/site-packages/pyminhash/pyminhash.py?line=77)[     Apply minhashing to the column `sparse_vector` in Pandas dataframe `df` in the new column `minhash_signature`.
     ]()[79](file:///~/miniconda2/envs/py395dd/lib/python3.9/site-packages/pyminhash/pyminhash.py?line=78)[     In addition, one column (e.g.: 'hash_{0}') per hash table is created.
   (...)
     ]()[86](file:///~/miniconda2/envs/py395dd/lib/python3.9/site-packages/pyminhash/pyminhash.py?line=85)[ 
     ]()[87](file:///~/miniconda2/envs/py395dd/lib/python3.9/site-packages/pyminhash/pyminhash.py?line=86)[     """
---> ]()[88](file:///~/miniconda2/envs/py395dd/lib/python3.9/site-packages/pyminhash/pyminhash.py?line=87)[     df['minhash_signature'] = df['sparse_vector'].apply(self._create_minhash)
     ]()[89](file:///~/miniconda2/envs/py395dd/lib/python3.9/site-packages/pyminhash/pyminhash.py?line=88)[     # the following involved way of creating 'hash_' columns prevents efficiency warnings
     ]()[90](file:///~/miniconda2/envs/py395dd/lib/python3.9/site-packages/pyminhash/pyminhash.py?line=89)[     hash_df = df['minhash_signature'].apply(pd.Series)

File ~/miniconda2/envs/py395dd/lib/python3.9/site-packages/pandas/core/series.py:4433, in Series.apply(self, func, convert_dtype, args, **kwargs)
   ]()[4323](file:///~/miniconda2/envs/py395dd/lib/python3.9/site-packages/pandas/core/series.py?line=4322)[ def apply(
   ]()[4324](file:///~/miniconda2/envs/py395dd/lib/python3.9/site-packages/pandas/core/series.py?line=4323)[     self,
   ]()[4325](file:///~/miniconda2/envs/py395dd/lib/python3.9/site-packages/pandas/core/series.py?line=4324)[     func: AggFuncType,
   (...)
   ]()[4328](file:///~/miniconda2/envs/py395dd/lib/python3.9/site-packages/pandas/core/series.py?line=4327)[     **kwargs,
   ]()[4329](file:///~/miniconda2/envs/py395dd/lib/python3.9/site-packages/pandas/core/series.py?line=4328)[ ) -> DataFrame | Series:
   ]()[4330](file:///~/miniconda2/envs/py395dd/lib/python3.9/site-packages/pandas/core/series.py?line=4329)[     """
   ]()[4331](file:///~/miniconda2/envs/py395dd/lib/python3.9/site-packages/pandas/core/series.py?line=4330)[     Invoke function on values of Series.
   ]()[4332](file:///~/miniconda2/envs/py395dd/lib/python3.9/site-packages/pandas/core/series.py?line=4331)[ 
   (...)
   ]()[4431](file:///~/miniconda2/envs/py395dd/lib/python3.9/site-packages/pandas/core/series.py?line=4430)[     dtype: float64
   ]()[4432](file:///~/miniconda2/envs/py395dd/lib/python3.9/site-packages/pandas/core/series.py?line=4431)[     """
-> ]()[4433](file:///~/miniconda2/envs/py395dd/lib/python3.9/site-packages/pandas/core/series.py?line=4432)[     return SeriesApply(self, func, convert_dtype, args, kwargs).apply()

File ~/miniconda2/envs/py395dd/lib/python3.9/site-packages/pandas/core/apply.py:1082, in SeriesApply.apply(self)
   ]()[1078](file:///~/miniconda2/envs/py395dd/lib/python3.9/site-packages/pandas/core/apply.py?line=1077)[ if isinstance(self.f, str):
   ]()[1079](file:///~/miniconda2/envs/py395dd/lib/python3.9/site-packages/pandas/core/apply.py?line=1078)[     # if we are a string, try to dispatch
   ]()[1080](file:///~/miniconda2/envs/py395dd/lib/python3.9/site-packages/pandas/core/apply.py?line=1079)[     return self.apply_str()
-> ]()[1082](file:///~/miniconda2/envs/py395dd/lib/python3.9/site-packages/pandas/core/apply.py?line=1081)[ return self.apply_standard()

File ~/miniconda2/envs/py395dd/lib/python3.9/site-packages/pandas/core/apply.py:1137, in SeriesApply.apply_standard(self)
   ]()[1131](file:///~/miniconda2/envs/py395dd/lib/python3.9/site-packages/pandas/core/apply.py?line=1130)[         values = obj.astype(object)._values
   ]()[1132](file:///~/miniconda2/envs/py395dd/lib/python3.9/site-packages/pandas/core/apply.py?line=1131)[         # error: Argument 2 to "map_infer" has incompatible type
   ]()[1133](file:///~/miniconda2/envs/py395dd/lib/python3.9/site-packages/pandas/core/apply.py?line=1132)[         # "Union[Callable[..., Any], str, List[Union[Callable[..., Any], str]],
   ]()[1134](file:///~/miniconda2/envs/py395dd/lib/python3.9/site-packages/pandas/core/apply.py?line=1133)[         # Dict[Hashable, Union[Union[Callable[..., Any], str],
   ]()[1135](file:///~/miniconda2/envs/py395dd/lib/python3.9/site-packages/pandas/core/apply.py?line=1134)[         # List[Union[Callable[..., Any], str]]]]]"; expected
   ]()[1136](file:///~/miniconda2/envs/py395dd/lib/python3.9/site-packages/pandas/core/apply.py?line=1135)[         # "Callable[[Any], Any]"
-> ]()[1137](file:///~/miniconda2/envs/py395dd/lib/python3.9/site-packages/pandas/core/apply.py?line=1136)[         mapped = lib.map_infer(
   ]()[1138](file:///~/miniconda2/envs/py395dd/lib/python3.9/site-packages/pandas/core/apply.py?line=1137)[             values,
   ]()[1139](file:///~/miniconda2/envs/py395dd/lib/python3.9/site-packages/pandas/core/apply.py?line=1138)[             f,  # type: ignore[arg-type]
   ]()[1140](file:///~/miniconda2/envs/py395dd/lib/python3.9/site-packages/pandas/core/apply.py?line=1139)[             convert=self.convert_dtype,
   ]()[1141](file:///~/miniconda2/envs/py395dd/lib/python3.9/site-packages/pandas/core/apply.py?line=1140)[         )
   ]()[1143](file:///~/miniconda2/envs/py395dd/lib/python3.9/site-packages/pandas/core/apply.py?line=1142)[ if len(mapped) and isinstance(mapped[0], ABCSeries):
   ]()[1144](file:///~/miniconda2/envs/py395dd/lib/python3.9/site-packages/pandas/core/apply.py?line=1143)[     # GH#43986 Need to do list(mapped) in order to get treated as nested
   ]()[1145](file:///~/miniconda2/envs/py395dd/lib/python3.9/site-packages/pandas/core/apply.py?line=1144)[     #  See also GH#25959 regarding EA support
   ]()[1146](file:///~/miniconda2/envs/py395dd/lib/python3.9/site-packages/pandas/core/apply.py?line=1145)[     return obj._constructor_expanddim(list(mapped), index=obj.index)

File ~/miniconda2/envs/py395dd/lib/python3.9/site-packages/pandas/_libs/lib.pyx:2870, in pandas._libs.lib.map_infer()

File ~/miniconda2/envs/py395dd/lib/python3.9/site-packages/pyminhash/pyminhash.py:73, in MinHash._create_minhash(self, doc)
     ]()[71](file:///~/miniconda2/envs/py395dd/lib/python3.9/site-packages/pyminhash/pyminhash.py?line=70)[ hashes += self.b
     ]()[72](file:///~/miniconda2/envs/py395dd/lib/python3.9/site-packages/pyminhash/pyminhash.py?line=71)[ hashes %= self.next_prime
---> ]()[73](file:///~/miniconda2/envs/py395dd/lib/python3.9/site-packages/pyminhash/pyminhash.py?line=72)[ minhashes = hashes.min(axis=0)
     ]()[74](file:///~/miniconda2/envs/py395dd/lib/python3.9/site-packages/pyminhash/pyminhash.py?line=73)[ return minhashes

File ~/miniconda2/envs/py395dd/lib/python3.9/site-packages/numpy/core/_methods.py:44, in _amin(a, axis, out, keepdims, initial, where)
     ]()[42](file:///~/miniconda2/envs/py395dd/lib/python3.9/site-packages/numpy/core/_methods.py?line=41)[ def _amin(a, axis=None, out=None, keepdims=False,
     ]()[43](file:///~/miniconda2/envs/py395dd/lib/python3.9/site-packages/numpy/core/_methods.py?line=42)[           initial=_NoValue, where=True):
---> ]()[44](file:///~/miniconda2/envs/py395dd/lib/python3.9/site-packages/numpy/core/_methods.py?line=43)[     return umr_minimum(a, axis, None, out, keepdims, initial, where)

ValueError: zero-size array to reduction operation minimum which has no identity]()

**Comment by fritshermans** [comment]
thanks for notifying me, could you please check the fix at https://github.com/fritshermans/pyminhash/tree/bugfix_zero_length_vectors

**Comment by gregskol** [comment]
HI, thanks for the quick response.

I installed the development version but I am still getting the same error.

Were you able to run

> myHasher = MinHash(n_hash_tables=10)
> myHasher.fit_predict(df, 'name')

on the example above?

(Btw, I am relatively new to python so apologies beforehand if I've done a mistake.)

**Comment by fritshermans** [comment]
yes I encountered the same error but it was fixed with the bug fix. Are you sure that you use the right code?

**Comment by fritshermans** [comment]
if you still encounter the issue, please raise it in PyMinHash.

**Comment by gregskol** [comment]
Hi thanks again, i was at the main branch when I was getting the error.
all fixed now, thanks for speedy response!
