### ISSUE TITLE
Importing deduplipy fails due to modAL dependency (google colab)

### ISSUE THREAD

**Issue by bingbong-sempai** [fritshermans/deduplipy#26]
It works when I run `pip install modAL-python` before installing deduplipy

**Comment by fritshermans** [comment]
this is a change in modal, it's reported

https://github.com/modAL-python/modAL/issues/170

if they don't fix it i will update deduplipy

**Comment by fritshermans** [comment]
apparently the name of modal has changed. i updated deduplipy accordingly
