### ISSUE TITLE
Handle abbreviations

### ISSUE THREAD

**Issue by Pacman1984** [fritshermans/deduplipy#8]
Maybe it would be a nice enhancement to implement a logic for handling abbreviation. 
E.g. VW = Volkswagen etc...

**Comment by fritshermans** [comment]
Do you mean as a blocking rule? That would be a good idea to implement. Please feel free to make a pull request.

**Comment by Pacman1984** [comment]
I think this should be handled before the blocking rule or am i wrong?

**Comment by fritshermans** [comment]
I suggest you create a string similarity metric that checks for abbreviations, something like: 

```
def check_abbreviation(x,y):
    if len(x)>len(y):
        short_string = y
        long_string = x
    else:
        short_string = x
        long_string = y
    words = long_string.split()
    first_letters_long_string = "".join([x[0] for x in words])
    return int(first_letters_long_string==short_string)
```

this would return 1 for:

`check_abbreviation('bmw', 'bayerische motoren werke')`

You can also create a blocking rule that creates a three letter abbreviation, something like this:
```
def three_letter_abbreviation(x):
    if len(x)==3:
        return x
    else:
        words = long_string.split()
        return "".join([x[0] for x in words[:3]])
```
which returns 'bmw' for both `three_letter_abbreviation('bayerische motoren werke')` and `three_letter_abbreviation('bmw')`
Obviously you can adjust the above to include abbreviations of different lengths.
Both the string similarity metric and the blocking rule can be added as arguments to the `Deduplicator` instance.
